# This is the PRODUCTION version of config_local.yml

# Database credentials.
database:
  driver: mysql
  databasename: bolt
  username: database_user
  password: 'hunter42'

# Debug settings
debug: false
debug_error_level: 8181
strict_variables: false
